### ISSUE TITLE
switch to protocol buffers

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-engine#3]
If sticking with json need to add a schema.

Switching to protocol buffers could another option. 

Pros:
* typed languages get the objects generated for free (if there is a protobuf implementation)
  * A lot of popular languages are supported:
https://developers.google.com/protocol-buffers/docs/reference/overview
  * Series of third-party implementations: https://github.com/google/protobuf/blob/master/docs/third_party.md

Cons:
* Debugging the messages back and forth may be harder (the binary already has a debug option that prints what it sends / receives so should be able to be adopted)
* Could be a limiting feature work for a language if protbuf is not yet implemented (json has same problem but is more prominent and thus less likely to be an issue)

**Comment by charlierudolph** [comment]
Some initial work for protocol buffers is on the branch `cr-protobuf`. This will require defining proto messages for the gherkin pickle and all the events. Will probably want to move the proto definitions into their own repo.

**Comment by aslakhellesoy** [comment]
Excited to see protobuf tsking shape! I’d prefer to go down the protobuf route for now. Code generation for protobuf is way better than for JSONSchema, so that will save us some coding - there are losts of message types.

If a language doesn’t have protobuf we can add JSON back. I think people will want protobuf in a language before they want Cucumber, so I think the chances are slim we’ll have to. Even Nim has protobuf!

**Comment by charlierudolph** [comment]
Done in 0c27ca853995dccaa21259dbe3593b965ccab702
